### ISSUE TITLE
Couldn't load plugin 'gis4wrf' Due to classfactory() method

### ISSUE THREAD

**Issue by leahpope** [GIS4WRF/gis4wrf#178] opened 2020-08-18 16:56 UTC
Below is the error I got when I tried to install the gis4wrf plugin in QGIS 3.14. I tried on different computers with the same error. I am running on windows. 

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\nthes\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\nthes\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\nthes\AppData\Local\gis4wrf\python37C:\OSGeo4W\bin\python-qgis.bat -m pip install --prefix C:\Users\nthes\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlERROR: wrf_python-1.3.2-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform. 
Traceback (most recent call last):
  File "C:/Users/nthes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:/Users/nthes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 220, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "C:/Users/nthes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 249, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['C:\\OSGeo4W\\bin\\python-qgis.bat', '-m', 'pip', 'install', '--prefix', 'C:\\Users\\nthes\\AppData\\Local\\gis4wrf\\python37', 'f90nml==1.0.2', 'netCDF4==1.4.2', 'https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/nthes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:/Users/nthes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\nthes\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\nthes\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\nthes\AppData\Local\gis4wrf\python37C:\OSGeo4W\bin\python-qgis.bat -m pip install --prefix C:\Users\nthes\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlERROR: wrf_python-1.3.2-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] 
QGIS version: 3.14.15-Pi Pi, d5114d2cfa

**Comment by letmaik** [comment] 2020-08-18 19:40
Duplicate of https://github.com/GIS4WRF/gis4wrf/issues/175. Please wait for the next release which should be out by tomorrow or so.

**Closed by letmaik** 2020-08-18 19:40 UTC

**Comment by dmey** [comment] 2020-08-19 07:30
@leahpope version 0.14.3 is now available, please restart QGIS and install GIS4WRF 0.14.3.
