### ISSUE TITLE
Can not visualize the results 

### ISSUE THREAD

**Issue by mostamndi** [GIS4WRF/gis4wrf#37] opened 2018-09-09 18:45 UTC
When i try to visualize the results it gives me this error: 
I am using QGIS3.2 on Ubuntu 18.4 
Thanks

`An error has occurred while executing Python code: 

TypeError: Value is not an int or float type: 
Traceback (most recent call last):
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_view.py", line 209, in on_variable_selected
    self.replace_variable_layer()
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_view.py", line 249, in replace_variable_layer
    dataset.path, variable.name, extra_dim_index, interp_level, interp_vert_name)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/transforms/wrf_netcdf_to_gdal.py", line 154, in convert_wrf_nc_var_to_gdal_dataset
    geo_transform = get_geo_transform(ds, crs)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/transforms/wrf_netcdf_to_gdal.py", line 418, in get_geo_transform
    lower_left_u = LonLat(lon=lons_u[t,0,0], lat=lats_u[t,0,0])
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/crs.py", line 23, in __init__
    super().__init__(lon, lat)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/crs.py", line 11, in __init__
    self.x = as_float(x)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/util.py", line 43, in as_float
    raise TypeError('Value is not an int or float type: {}'.format(type(val)))
TypeError: Value is not an int or float type: 

Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
QGIS version: 3.2.2-Bonn Bonn, 2684216 

Python Path:
/usr/share/qgis/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/suleiman/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/gis4wrf/python/local/lib/python3.6/dist-packages
/home/suleiman/.local/share/gis4wrf/python/lib/python3/dist-packages
/home/suleiman/.local/share/gis4wrf/python/lib/python3.6/dist-packages`
`

Thanks!!

**Comment by dmey** [comment] 2018-09-10 07:45
Duplicate of #36.

**Closed by dmey** 2018-09-10 07:45 UTC
Labels: duplicate
