### ISSUE TITLE
ERROR: Data not found in ungrib when using ds084.1 "168-hour Forecast" met data

### ISSUE THREAD

**Issue by raffyjef** [GIS4WRF/gis4wrf#182] opened 2020-09-05 12:14 UTC
I've tried running GIS4WRF and its working for analysis data. However, when I tried using it for datasets 168-hr forecast under ds084.1, the ungrib process is not working. It gives a message of data not found even if the data is in the directed folder.

**Comment by letmaik** [comment] 2020-09-06 09:53
Can you list the start/end date and possible subset of the met dataset you use? Also, please copy paste the full terminal output of the ungrib run, or at least enough to see the exact error message.

**Comment by letmaik** [comment] 2020-09-06 10:41
FWIW, I could reproduce this with the tutorial project using the same date/times just replacing the met dataset with ds084.1 168-hour Forecast. The metadata of the grib files is read correctly by gis4wrf as 2018-07-08 12:00 - 2018-07-08 18:00 but for some reason ungrib is not happy with it:
```
 *** Starting program ungrib.exe ***
Start_date =  2018-07-08_12:00:00 ,      End_date = 2018-07-08_18:00:00
output format is WPS
Path to intermediate files is ./
Subroutine DATINT: Interpolating 3-d files to fill in any missing data...
Looking for data at time 2018-07-08_12
ERROR: Data not found: 2018-07-08_12:00:00.0000
```

@raffyjef I would suggest asking about this in the WRF forums as it doesn't seem to be a gis4wrf issue. I would be interested to know why it fails and whether this condition can be detected in advance to guide the user.

**Comment by raffyjef** [comment] 2020-09-06 10:46
Yes, that's the same error message I have. I will try to ask about it in WRF forums. If ever you were able to find out about it before me, kindly message me. I appreciate your help a lot. Thank you!

**Comment by raffyjef** [comment] 2020-09-06 13:52
Someone replied that since it is a 168-hour forecast, the start_date should be  =  2018-07-15_12:00:00  and End_date = 2018-07-15_18:00:00 in the namelist.wps

**Comment by letmaik** [comment] 2020-09-06 14:10
Could you paste the link to the forum post?

**Comment by raffyjef** [comment] 2020-09-06 14:46
I've seen this forum and it seems that he solved it by upgrading WRF.

https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=48&t=8313&p=13906&hilit=ungrib.exe+problem+missing#p13906

**Comment by letmaik** [comment] 2020-09-06 18:08
> Someone replied that since it is a 168-hour forecast, the start_date should be = 2018-07-15_12:00:00 and End_date = 2018-07-15_18:00:00 in the namelist.wps

I meant the forum post of this statement. Can you post a link please?

**Comment by raffyjef** [comment] 2020-09-07 00:26
Hi! Sorry but I cannot find the link anymore. Please update me if ever you
have found the problem for this. Thanks!

**Comment by raffyjef** [comment] 2020-09-07 10:13
I've also tried using ds083.3 3-hour forecast and it has also the same
problem. I think it has the same problem for all forecast dataset


Command: C:\Users\serd\Documents\gis4wrf\dist\WPS-4.0-mpi\ungrib.exe

Working directory:
C:/Users/serd/Documents/gis4wrf/projects/Armsterdam\run_wps

*** Starting program ungrib.exe ***

Start_date = 2020-09-04_00:00:00 , End_date = 2020-09-05_00:00:00

output format is WPS

Path to intermediate files is ./


###############################################################################


Inventory for date = 2020-09-04 03:00:00


PRES TT UU VV RH HGT PSFC PMSL SM000010 SM010040 SM040100 SM100200 SM010200
ST000010 ST010040 ST040100 ST100200 ST010200 SEAICE LANDSEA SOILHGT
SKINTEMP SNOW SNOWH UMAXW VMAXW PMAXW TMAXW HGTMAXW UTROP VTROP PTROP TTROP
HGTTROP

-------------------------------------------------------------------------------

2013.0 O O O O O O X O O O O O O O O O O O O O O O O O O O O O O O O O O

2001.0 X X X X O X O X X X X O X X X X O X X X X X O X X X X X X X X X X

1000.0 X X X X X

975.0 X X X X X

950.0 X X X X X

925.0 X X X X X

900.0 X X X X X

850.0 X X X X X

800.0 X X X X X

750.0 X X X X X

700.0 X X X X X

650.0 X X X X X

600.0 X X X X X

550.0 X X X X X

500.0 X X X X X

450.0 X X X X X

400.0 X X X X X

350.0 X X X X X

300.0 X X X X X

250.0 X X X X X

200.0 X X X X X

150.0 X X X X X

100.0 X X X X X

70.0 X X X X X

50.0 X X X X X

40.0 X X

30.0 X X X X X

20.0 X X X X X

15.0 X X

10.0 X X X X X

7.0 X X X X X

5.0 X X X X X

3.0 X X X X X

2.0 X X X X X

1.0 X X X X X

-------------------------------------------------------------------------------


###############################################################################


Inventory for date = 2020-09-04 09:00:00


PRES TT UU VV RH HGT PSFC PMSL SM000010 SM010040 SM040100 SM100200 SM010200
ST000010 ST010040 ST040100 ST100200 ST010200 SEAICE LANDSEA SOILHGT
SKINTEMP SNOW SNOWH UMAXW VMAXW PMAXW TMAXW HGTMAXW UTROP VTROP PTROP TTROP
HGTTROP

-------------------------------------------------------------------------------

2013.0 O O O O O O X O O O O O O O O O O O O O O O O O O O O O O O O O O

2001.0 X X X X O X O X X X X O X X X X O X X X X X O X X X X X X X X X X

1000.0 X X X X X

975.0 X X X X X

950.0 X X X X X

925.0 X X X X X

900.0 X X X X X

850.0 X X X X X

800.0 X X X X X

750.0 X X X X X

700.0 X X X X X

650.0 X X X X X

600.0 X X X X X

550.0 X X X X X

500.0 X X X X X

450.0 X X X X X

400.0 X X X X X

350.0 X X X X X

300.0 X X X X X

250.0 X X X X X

200.0 X X X X X

150.0 X X X X X

100.0 X X X X X

70.0 X X X X X

50.0 X X X X X

40.0 X X

30.0 X X X X X

20.0 X X X X X

15.0 X X

10.0 X X X X X

7.0 X X X X X

5.0 X X X X X

3.0 X X X X X

2.0 X X X X X

1.0 X X X X X

-------------------------------------------------------------------------------


###############################################################################


Inventory for date = 2020-09-04 15:00:00


PRES TT UU VV RH HGT PSFC PMSL SM000010 SM010040 SM040100 SM100200 SM010200
ST000010 ST010040 ST040100 ST100200 ST010200 SEAICE LANDSEA SOILHGT
SKINTEMP SNOW SNOWH UMAXW VMAXW PMAXW TMAXW HGTMAXW UTROP VTROP PTROP TTROP
HGTTROP

-------------------------------------------------------------------------------

2013.0 O O O O O O X O O O O O O O O O O O O O O O O O O O O O O O O O O

2001.0 X X X X O X O X X X X O X X X X O X X X X X O X X X X X X X X X X

1000.0 X X X X X

975.0 X X X X X

950.0 X X X X X

925.0 X X X X X

900.0 X X X X X

850.0 X X X X X

800.0 X X X X X

750.0 X X X X X

700.0 X X X X X

650.0 X X X X X

600.0 X X X X X

550.0 X X X X X

500.0 X X X X X

450.0 X X X X X

400.0 X X X X X

350.0 X X X X X

300.0 X X X X X

250.0 X X X X X

200.0 X X X X X

150.0 X X X X X

100.0 X X X X X

70.0 X X X X X

50.0 X X X X X

40.0 X X

30.0 X X X X X

20.0 X X X X X

15.0 X X

10.0 X X X X X

7.0 X X X X X

5.0 X X X X X

3.0 X X X X X

2.0 X X X X X

1.0 X X X X X

-------------------------------------------------------------------------------


###############################################################################


Inventory for date = 2020-09-04 21:00:00


PRES TT UU VV RH HGT PSFC PMSL SM000010 SM010040 SM040100 SM100200 SM010200
ST000010 ST010040 ST040100 ST100200 ST010200 SEAICE LANDSEA SOILHGT
SKINTEMP SNOW SNOWH UMAXW VMAXW PMAXW TMAXW HGTMAXW UTROP VTROP PTROP TTROP
HGTTROP

-------------------------------------------------------------------------------

2013.0 O O O O O O X O O O O O O O O O O O O O O O O O O O O O O O O O O

2001.0 X X X X O X O X X X X O X X X X O X X X X X O X X X X X X X X X X

1000.0 X X X X X

975.0 X X X X X

950.0 X X X X X

925.0 X X X X X

900.0 X X X X X

850.0 X X X X X

800.0 X X X X X

750.0 X X X X X

700.0 X X X X X

650.0 X X X X X

600.0 X X X X X

550.0 X X X X X

500.0 X X X X X

450.0 X X X X X

400.0 X X X X X

350.0 X X X X X

300.0 X X X X X

250.0 X X X X X

200.0 X X X X X

150.0 X X X X X

100.0 X X X X X

70.0 X X X X X

50.0 X X X X X

40.0 X X

30.0 X X X X X

20.0 X X X X X

15.0 X X

10.0 X X X X X

7.0 X X X X X

5.0 X X X X X

3.0 X X X X X

2.0 X X X X X

1.0 X X X X X

-------------------------------------------------------------------------------

Subroutine DATINT: Interpolating 3-d files to fill in any missing data...

Looking for data at time 2020-09-04_00

ERROR: Data not found: 2020-09-04_00:00:00.0000

Runtime: 0 s

**Comment by raffyjef** [comment] 2020-09-07 11:15
I think the problem is with GIS4WRF, from the given ungrib log it was able
to find the following Inventory for date = 2020-09-04 03:00:00  , 2020-09-04
09:00:00 ,  2020-09-04 15:00:00, &  2020-09-04 21:00:00. It means that the
proper start_date in the namelist.wps is '2020-09-04_03:00:00' and end_date
= '2020-09-05_03:00:00'. Kindly message me if you got my point. Thank you
very much!

**Comment by letmaik** [comment] 2020-09-07 17:44
The logic currently is to take the min/max time found in the GRIB files. If this is not correct (and it looks like it) then it should be fixed. If you can figure out the rules and how to compute the right start/stop times given a set of GRIB files, then we can fix it. So far, it's not very clear, at least to me.

**Comment by raffyjef** [comment] 2020-09-07 18:02
For forecast files,  the logic is to basically add the forecast hours to
the  analysis time. If its a 168-hour forecast dataset add +168 hours to
the start and end date. If its a 3-hour forecast dataset, add +3 hours,..
etc.

**Comment by raffyjef** [comment] 2020-09-07 18:03
So basically add the forecast hours to the min and max time found in the
grib file

**Comment by letmaik** [comment] 2020-09-07 18:13
Is there a way to detect whether a dataset is a forecast dataset? How does WRF know it?

**Comment by raffyjef** [comment] 2020-09-07 18:37
I hope this intro to grib2 pdf will help. Using the wgrib (which I haven't
tried using yet), you can look into the grib2 file.

Example mentioned in the paper:

Here are lines 4 and 5 of the above inventory:
3:337239:d=2013020806:HGT:10 mb:12 hour fcst:
4:571416:d=2013020806:TMP:10 mb:12 hour fcst:
The first line says the message
 “3” grib message number 3
 “337239” message starts at byte location 337239 and ends at 571415
 571415 is one less than the start of the next message
 “d=2013020806” forecast started at 06Z Feb 8, 2013020805
 “HGT” the field is the geopotential height in geopotential meters (see
NCEP tables)
 “10 mb” the field for 10 mb or 100 hPa.
 “12 hour fcst” the field is a 12 hour forecast from the intial time
2013020806


From the lines it shows that it is a 12 hour forecast. I hope this will
help. Thank you!

**Comment by raffyjef** [comment] 2020-09-07 18:42
Also in the filename, it can be seen as a forecast dataset.

Example:
 gfs.0p25.2018070812.f168.grib2,  gfs.0p25.2018070818.f168.grib2

The .f168 part shows that it is a forecast dataset file.

**Comment by letmaik** [comment] 2020-09-07 21:25
I may have found a solution to this, see https://github.com/GIS4WRF/gis4wrf/pull/189.

If you want to try it out, please re-install the plugin from this zip file: [gis4wrf.zip](https://github.com/GIS4WRF/gis4wrf/files/5184937/gis4wrf.zip).

**Comment by raffyjef** [comment] 2020-09-07 22:35
It's working now! Thanks a lot for being responsive.

Regards,
Jeff

**Closed** 2020-09-09 07:11 UTC
Labels: bug
