### ISSUE TITLE
Cannot connect to RDA server through proxy

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#25] opened 2018-07-08 17:15 UTC
@kikocorreoso reported an issue when connecting to the RDA server through proxy (moved from #23):
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='rda.ucar.edu', port=443): Max retries exceeded with url: /apps/metadata/ds083.3 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:749)'),)) 
Traceback (most recent call last):
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\QGIS\apps\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "D:\QGIS\apps\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "D:\QGIS\apps\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "D:\QGIS\apps\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\QGIS\apps\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\QGIS\apps\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rda.ucar.edu', port=443): Max retries exceeded with url: /apps/metadata/ds083.3 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:749)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/U406328/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_met.py", line 126, in on_dataset_changed
    self.products = get_met_products(dataset_name, auth)
  File "C:/Users/U406328/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\core\downloaders\met.py", line 22, in get_met_products
    response = requests_retry_session().get(f'https://rda.ucar.edu/apps/metadata/{dataset_name}', auth=auth)
  File "D:\QGIS\apps\Python36\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\QGIS\apps\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\QGIS\apps\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\QGIS\apps\Python36\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='rda.ucar.edu', port=443): Max retries exceeded with url: /apps/metadata/ds083.3 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:749)'),))


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.0-Bonn Bonn, bc43194061
```

**Comment by dmey** [comment] 2018-07-08 17:21
@kikocorreoso can you let me know if you can connect and log-in using your web browser? For example: https://rda.ucar.edu/datasets/ds083.3/.

**Comment by kikocorreoso** [comment] 2018-07-09 07:17
@dmey I can access via webbrowser.

If I try thredds using `requests` on NCSS (NetCDF subset) using this code:

```python
import requests

requests.get("https://rda.ucar.edu/thredds/ncss/grid/files/g/ds083.3/2018/201807gdas1.fnl0p25.2018070100.f00.grib2?var=Relative_humidity_sigma_layer&disableLLSubset=on&horizStride=1&time_start=2018-07-01T00%3A00%3A00Z&time_end=2018-07-01T00%3A00%3A00Z&timeStride=1&vertCoord=&accept=netcdf3", auth=('user', 'pass'))
```

I get a similar error.

I've updated `requests`, `pyopenssl`, `certifi`,..., but the issue still persists. But it seems the problem is not related with GIS4WRF itself and it is something related with requests or windows or the setup of my corporate computer,...

**Comment by letmaik** [comment] 2018-07-09 07:46
The `requests` library (and others) uses the `HTTP_PROXY` and `HTTPS_PROXY` environment variables (also on Windows). Maybe the problem is simply that `requests` doesn't pick up your system proxy settings. It would be a little strange though since you said that you can access other URLs via `requests`. Try this from the command line:
```
setx HTTPS_PROXY http://10.10.1.10:3128
```
And adjust IP/port to whatever your proxy is. Then try again, note you need to re-open the command prompt for the environment variable to be visible.

**Comment by kikocorreoso** [comment] 2018-07-09 07:59
@letmaik I think the proxy settings is not the problem. I use both `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

I can access most of the internet from the corporate computer (from the browser, using curl, using python,...) but there is a problem to access rda.ucar.edu from this computer (I can access from the browser but not using curl nor python) so maybe it is a problem of my corporate computer that uses something wrong for this specific page. ¿?

I've tried to update requests (2.18.4 -> 2.19.1) and other related libs with no luck so I suppose it is something related with the custom windows box I'm using.

I can try another windows at home using a Virtual Machine to try to check if it is just the corporate windows. I will close the issue in the meanwhile and reopen if with other windows I can see the same issue.

**Comment by letmaik** [comment] 2018-07-09 08:10
OK, I'll close it for now.

**Closed by letmaik** 2018-07-09 08:10 UTC
Labels: bug

**Comment by uranoscopus** [comment] 2019-07-25 12:23
I have the same problem....was it solved?

**Comment by dmey** [comment] 2019-07-25 13:02
The issue seemed to only apply to the proxy configuration with @kikocorreoso -- see https://github.com/GIS4WRF/gis4wrf/issues/25#issuecomment-403393482. Please make sure to check you configuration and see if you can even access rda.ucar.edu using  e.g. curl or, better, using python with requests as we do from the command line.

**Comment by uranoscopus** [comment] 2019-07-25 13:12
I cannot access even through python- requests....it returns to me a reply 401....with no text attached. I also updated requests...on both python versions I have in my Mac (to be safe).
Any ideas?
