### ISSUE TITLE
Set to Canvas Extent causes crash

### ISSUE THREAD

**Issue by TechEdd** [GIS4WRF/gis4wrf#203] opened 2021-01-19 01:23 UTC
Hi,
I've been trying to run a WRF simulation, but QGIS crash when I click on Set to Canvas Extent.
Opening the project back makes it crash again.
I tried on two different computers and would like if there is something I don't do right.

```
Crash ID: 1a914b67d264a45bb2b2f081358e7034abd79f14


Stack Trace


PyModule_Create2 :
PyInit__ctypes :
PyUnicode_EncodeCharmap :
PyUnicode_EncodeCharmap :
PyUnicode_EncodeCharmap :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyDict_GetItemString :
PyException_SetTraceback :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyImport_ImportFrozenModuleObject :
PyImport_ExecCodeModuleObject :
PyImport_ExecCodeModuleWithPathnames :
VRTDerivedRasterBand::InitializePython :
VRTDerivedRasterBand::IRasterIO :
VRTSourcedRasterBand::IReadBlock :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::ComputeStatistics :
GDALRasterBand::GetStatistics :
QgsGdalProvider::bandStatistics qgsgdalprovider.cpp:2787
QgsRasterLayer::computeMinMax qgsrasterlayer.cpp:981
QgsRasterLayer::setContrastEnhancement qgsrasterlayer.cpp:1093
QgsRasterLayer::setDefaultContrastEnhancement qgsrasterlayer.cpp:1413
QgsRasterLayer::setDataSource qgsrasterlayer.cpp:954
QgsRasterLayer::QgsRasterLayer qgsrasterlayer.cpp:132
sipQgsRasterLayer::sipQgsRasterLayer sip_corepart3.cpp:14006
init_type_QgsRasterLayer sip_corepart3.cpp:18849
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PySeqIter_New :
PyObject_GenericSetAttrWithDict :
PyObject_SetAttr :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
PyInit_QtCore :
PyInit_QtCore :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.2-Hannover
QGIS code revision: f1660f9da5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
```

Thank you very much for your help! :)

**Comment by letmaik** [comment] 2021-01-19 07:53
Duplicate of https://github.com/GIS4WRF/gis4wrf/issues/202.

**Closed by letmaik** 2021-01-19 07:53 UTC
