### ISSUE TITLE
Create derived parameters

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#64] opened 2018-09-26 07:44 UTC
For analysis, it would be nice to create derived parameters. Example: wind speed magnitude, created from 2D fields U10 and V10, or 3D fields U and V.

**Comment by dmey** [comment] 2018-09-27 21:36
We rely on [wrf-python](https://github.com/NCAR/wrf-python) to compute diagnostics variables and to interpolate the data. If there are parameteres which are not currently supoorted, it may be better to suggest them to wrf-python directly [here](https://github.com/NCAR/wrf-python/issues) rather than implementing them from scratch in GIS4WRF. I will close this issue.

**Closed by dmey** 2018-09-27 21:36 UTC
Labels: enhancement, wontfix

**Comment by hugohartmann** [comment] 2018-09-28 07:35
@letmaik Thanks for this suggestion, will do!

**Comment by hugohartmann** [comment] 2018-09-28 07:44
Just one question and comment: The variables that have a * at the end of the parameter name (e.g. MDBZ*), are these referring to the diagnostics provided by wrf-python? It seems not always be the case as CLDFRA does not have a *.

I noticed that a lot of these * parameters have empty fields. MDBZ for instance. Perhaps I should forward this to wrf-python. 

Suggestion: please add the parameter unit and dimension (2D, 3D) to the parameter description

**Comment by letmaik** [comment] 2018-09-28 08:18
Yes, * means it's coming from wrf-python. CLDFRA is part of the NetCDF file, it's not derived and also isn't part of the list I linked above. Did you confuse that with something else?

Regarding empty fields, what do you mean by that?

Can you create a separate issue for your suggestion with the parameter units and dimension?

**Comment by hugohartmann** [comment] 2018-09-28 09:12
empty means 'black'.

![image](https://user-images.githubusercontent.com/16716578/46199126-87329e00-c30e-11e8-988d-8639e8ca020b.png)

This picture is showing MDBZ*. Perhaps it has (again) to do with the colorbar selection in "Symbology". I am seeing 49 bands. What is that? Does it happen to be the number of forecast hours that had been simulated?

**Comment by letmaik** [comment] 2018-09-30 15:10
The different bands are the different time steps. The time slider just switches the currently active band. I think the issue is that when the image is all black, then the min and max is the same value, and this scaling is kept for all time steps which would probably keep them black even if they have data. By manually fiddling you probably reset the min/max based on a different layer. This probably deserves a separate issue.

**Comment by hugohartmann** [comment] 2018-10-01 07:04
I will create one.

**Comment by dmey** [comment] 2018-12-19 12:37
Wspd and wdir has now been added as separate diagnostics variables in wrf-python (see: NCAR/wrf-python#73

**Comment by letmaik** [comment] 2018-12-19 17:53
@dmey This issue is not about wind vectors as such, but merely to be able to access what was combined in  `wspd_wdir` at all and what is now exposed as two separate 2D fields. There's nothing else from our side to do there. For Windows, it depends a bit on when wrf-python releases binary wheels for newer versions. On macOS/Linux, with the next release of wrf-python, the two new fields `wspd` and `wdir` can be accessed from GIS4WRF without any change. Note that drawing of vectors is part of #47 which requires more external work outside our control.
