### ISSUE TITLE
Python issue after update to QGIS 3.4.0

### ISSUE THREAD

**Issue by kastnerp** [GIS4WRF/gis4wrf#97] opened 2018-10-28 17:29 UTC
**Describe the bug**
After updateing to 3.4.0, I receive the following message just after gis4wrf tried to install the custom Python version.

> WARNING    warning:C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\status_codes.py:18: DeprecationWarning: invalid escape sequence \o

**To Reproduce**
1. Start QGIS 3.4.0 for the first time and install gis4wrf through the plugin manager

**Expected behavior**
Install the custom python version without throwing the exception.

**Screenshots**
-

**Operating System Information (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
-

**Comment by dmey** [comment] 2018-10-28 18:31
Hi @kastnerp, thanks for reporting this issue. Have you been able to install GIS4WRF on QGIS 3.4? I have just tried to launch QGIS 3.4 and noticed that there is an issue with the installation of the GIS4WRF dependencies and have opened an issue (see #98). Can you please confirm whether you are experiencing the same issue as reported in #98? I was not able to reproduce your `DeprecationWarning` issue but this should not cause the installation to fail.

**Comment by kastnerp** [comment] 2018-10-28 19:08
You are correct, it does not install. In fact, after starting the second time, I now get the same error you described in https://github.com/GIS4WRF/gis4wrf/issues/98.

**Comment by dmey** [comment] 2018-11-08 23:50
@kastnerp QGIS 3.4.1 has been released and it restores pip. We have also released a new patch release to re-support QGIS 3.4.x, Can you please upgrade to the latest version of QGIS (currently 3.4.1) and install/upgrade to GIS4WRF 0.13.2 and let us know if you are still having issues? Thanks

**Comment by letmaik** [comment] 2018-11-28 23:06
Closing. If this is still an issue, please let us know.

**Closed by letmaik** 2018-11-28 23:06 UTC
