### ISSUE TITLE
Unsupported axis order: Lat/Lon, must be Lon/Lat.

### ISSUE THREAD

**Issue by raffyjef** [GIS4WRF/gis4wrf#191] opened 2020-09-18 04:29 UTC
I am trying to convert SRTM dataset 1-arcsecond to WPS binary. However, I am receiving this message: Unsupported axis order: Lat/Lon, must be Lon/Lat. 

How do I solve this problem? Thank you.

**Comment by dmey** [comment] 2020-09-18 06:41
Duplicate of https://github.com/GIS4WRF/gis4wrf/issues/165. The new version should be available for download soon from https://plugins.qgis.org/plugins/gis4wrf/ but in the meantime you can download and install it manually from https://github.com/GIS4WRF/gis4wrf/issues/190

**Closed by dmey** 2020-09-18 06:41 UTC

**Comment by dmey** [comment] 2020-09-18 07:08
Version 0.14.4 is now available at https://plugins.qgis.org/plugins/gis4wrf/

**Comment by raffyjef** [comment] 2020-09-18 07:25
Thank you!
